[package]
name = "plonky2bench"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
plonky2 = "1.0.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }
